server:
  port: 8080
spring:
  application:
    name: online-book-store
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:online-book-store-db
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    com.bookstore: DEBUG
bookstore:
  api:
    cartMapping: api/cart/
    bookMapping: api/book/
    addCart: addCart
    modifyCart: modifyCart
    deleteCart: deleteCart
    listCart: listCart
    checkout: checkout
    listBooks: listBooks